### ISSUE TITLE
how do i run it??

### ISSUE THREAD

**Issue by johnnythecow1** [The6P4C/Kalkimg#2]
hi! i need help! how do i run it?? 
is there a way to use it without visual studio??
cheers

**Comment by the6p4c** [comment]
Hi!

Just download both the `Kalkimg.exe` and `Ionic.Zip.dll` file from the latest release in the [Releases](https://github.com/The6P4C/Kalkimg/releases) section into the same directory. You should then be able to run `Kalkimg.exe`.

Please get back to me if you have any problems.

Thanks.

**Comment by johnnythecow1** [comment]
sweet thanks so much!
